In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4421, 6518, 6599, 1703],
 [4421, 6518, 6599, 3505],
 [4421, 2373, 6599, 3615],
 [5848, 533, 731, 7326, 5888],
 [5848, 533, 731, 7326, 3105],
 [9944, 4421, 1194, 6599, 6251],
 [2662, 4214, 2550, 7326]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4421 6518 6599 1703]
 [   0    0    0    0 4421 6518 6599 3505]
 [   0    0    0    0 4421 2373 6599 3615]
 [   0    0    0 5848  533  731 7326 5888]
 [   0    0    0 5848  533  731 7326 3105]
 [   0    0    0 9944 4421 1194 6599 6251]
 [   0    0    0    0 2662 4214 2550 7326]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 145ms/step


array([[[-0.01006087, -0.03929988, -0.01514823,  0.02069249,
          0.03117787, -0.00727306, -0.04899403,  0.03824521,
          0.041681  , -0.02061715],
        [-0.01006087, -0.03929988, -0.01514823,  0.02069249,
          0.03117787, -0.00727306, -0.04899403,  0.03824521,
          0.041681  , -0.02061715],
        [-0.01006087, -0.03929988, -0.01514823,  0.02069249,
          0.03117787, -0.00727306, -0.04899403,  0.03824521,
          0.041681  , -0.02061715],
        [-0.01006087, -0.03929988, -0.01514823,  0.02069249,
          0.03117787, -0.00727306, -0.04899403,  0.03824521,
          0.041681  , -0.02061715],
        [ 0.02873245, -0.00924041,  0.03041634, -0.03666469,
         -0.04137453,  0.04100188,  0.01704447,  0.01661301,
         -0.02350903, -0.0005899 ],
        [-0.01823623,  0.03098002, -0.03847652, -0.02767537,
          0.00620202, -0.02361964,  0.00332933, -0.01457406,
          0.0400759 , -0.03250364],
        [-0.03944816,  0.04522571,  0.0181956 ,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 4421, 6518, 6599, 1703])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 49ms/step


array([[-0.01006087, -0.03929988, -0.01514823,  0.02069249,  0.03117787,
        -0.00727306, -0.04899403,  0.03824521,  0.041681  , -0.02061715],
       [-0.01006087, -0.03929988, -0.01514823,  0.02069249,  0.03117787,
        -0.00727306, -0.04899403,  0.03824521,  0.041681  , -0.02061715],
       [-0.01006087, -0.03929988, -0.01514823,  0.02069249,  0.03117787,
        -0.00727306, -0.04899403,  0.03824521,  0.041681  , -0.02061715],
       [-0.01006087, -0.03929988, -0.01514823,  0.02069249,  0.03117787,
        -0.00727306, -0.04899403,  0.03824521,  0.041681  , -0.02061715],
       [ 0.02873245, -0.00924041,  0.03041634, -0.03666469, -0.04137453,
         0.04100188,  0.01704447,  0.01661301, -0.02350903, -0.0005899 ],
       [-0.01823623,  0.03098002, -0.03847652, -0.02767537,  0.00620202,
        -0.02361964,  0.00332933, -0.01457406,  0.0400759 , -0.03250364],
       [-0.03944816,  0.04522571,  0.0181956 ,  0.00732679, -0.02170776,
        -0.04494518,  0.00566536, -0.02728318